subprojects {
    apply plugin: 'java'

    java.toolchain.languageVersion = JavaLanguageVersion.of(17)
    java.withSourcesJar()
    java.withJavadocJar()

    jar {
        from(rootProject.file("LICENSE")) {
            rename { "${it}_${mod_id}" }
        }
        manifest {
            attributes(['Specification-Title'     : mod_name,
                        'Specification-Vendor'    : authors,
                        'Specification-Version'   : project.jar.archiveVersion,
                        'Implementation-Title'    : project.name,
                        'Implementation-Version'  : project.jar.archiveVersion,
                        'Implementation-Vendor'   : authors,
                        'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                        'Timestamp'               : System.currentTimeMillis(),
                        'Built-On-Java'           : "${System.getProperty('java.vm.version')} (${System.getProperty('java.vm.vendor')})",
                        'Built-On-Minecraft'      : minecraft_version])
        }
    }

    sourcesJar {
        from(rootProject.file("LICENSE")) {
            rename { "${it}_${mod_name}" }
        }
    }

    repositories {
        mavenCentral()
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/" }
        maven { url = "https://dvs1.progwml6.com/files/maven/" }
        maven { url = "https://maven.blamejared.com/" }
        maven { url = "https://modmaven.dev" }
        maven { url = "https://www.cursemaven.com" }
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.encoding = 'UTF-8'
        it.options.getRelease().set(17)
    }

    processResources {
        def properties = ["projectGroup"              : project.group,
                          //Mod
                          "mod_id"                    : mod_id,
                          "mod_version"               : mod_version,
                          "mod_name"                  : mod_name,
                          //Minecraft
                          "minecraft_version"         : minecraft_version,
                          "minecraft_version_range"   : minecraft_version_range,
                          //Common
                          "authors"                   : authors,
                          "license"                   : license,
                          "credits"                   : credits,
                          "description"               : description,
                          "displayURL"                : displayURL,
                          "issueTrackerURL"           : issueTrackerURL,
                          "updateJSONURL"             : updateJSONURL,
                          //Forge
                          "forge_version"             : forge_version,
                          "forge_mod_version_range"   : forge_mod_version_range,
                          "forge_loader_version_range": forge_loader_version_range,
                          //Fabric
                          "fabric_version"            : fabric_version,
                          "fabric_loader_version"     : fabric_loader_version,
                          //Parchment mappings
                          "parchment_version"         : parchment_version,
                          //Optional dependencies
                          "jei_version"               : jei_version]

        filesMatching(['pack.mcmeta', 'fabric.mod.json', 'META-INF/mods.toml', '*.mixins.json', 'update.json']) {
            expand(properties)
        }

        inputs.properties(properties)
    }
}