#Project
project_group=darkorg.bettermaterials

#Mod
mod_id=bettermaterials
mod_version=1.0.3
mod_name=Better Materials

#Minecraft
minecraft_version=1.20.1
minecraft_version_range=[1.20.1, 1.21)

#Common
authors=Darkorg, Steffy Jones
license=MIT License
credits=Thanks for this mod goes to Java.
mod_description=A minecraft mod, expanding upon the vanilla game, making materials more useful and realistic.
displayURL=https://www.curseforge.com/minecraft/mc-mods/better-materials
issueTrackerURL=https://github.com/darkorg69/better-materials/issues
updateJSONURL=https://raw.githubusercontent.com/darkorg69/better-materials/1.20.1/update.json

#Forge
forge_version=47.4.8
forge_mod_version_range=[47,)
forge_loader_version_range=[47,)

# Fabric
fabric_version=0.92.6+1.20.1
fabric_loader_version=0.17.2

#NeoForge
neoforge_version=20.6.121
neoforge_loader_version_range=[4,)

#Dependencies
fcap_version=8.0.2
fcap_version_range=[8.0.2,)
forge_config_screens_version=8.0.2

#Optional
jei_version=15.20.0.106

#Parchment
parchment_version=2023.09.03

# Gradle
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false