modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT License"
issueTrackerURL = "https://github.com/darkorg69/better-materials/issues"

[[mods]]
modId = "bettermaterials"
version = "${file.jarVersion}"
displayName = "Better Materials"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/better-materials"
logoFile = "bettermaterials.png"
credits = "Thanks for this mod goes to Java and the Forge team."
authors = "Darkorg"
description = '''A minecraft mod, expanding upon vanilla resources, making them more useful and realistic.'''