modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT License"
issueTrackerURL = "https://github.com/darkorg69/better-materials/issues"

[[mods]]
modId = "bettermaterials"
version = "${file.jarVersion}"
displayName = "BetterMaterials"
#updateJSONURL=""
displayURL = "https://www.curseforge.com/minecraft/mc-mods/bettermaterials"
logoFile = "bettermaterials.png"
credits = "Thanks for this mod goes to Java and the Forge team."
authors = "Darkorg"
description = '''A minecraft mod, expanding upon vanilla resources, making them more useful and realistic.'''

[[dependencies.bettermaterials]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bettermaterials]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.20)"
ordering = "NONE"
side = "BOTH"